(function() {var implementors = {};
implementors["hyperlocal"] = [{text:"impl <a class=\"trait\" href=\"https://docs.rs/futures/0.1/futures/future/trait.Future.html\" title=\"trait futures::future::Future\">Future</a> for <a class=\"enum\" href=\"hyperlocal/client/enum.ConnectFuture.html\" title=\"enum hyperlocal::client::ConnectFuture\">ConnectFuture</a>",synthetic:false,types:["hyperlocal::client::ConnectFuture"]},{text:"impl&lt;F&gt; <a class=\"trait\" href=\"https://docs.rs/futures/0.1/futures/future/trait.Future.html\" title=\"trait futures::future::Future\">Future</a> for <a class=\"struct\" href=\"hyperlocal/server/struct.Connecting.html\" title=\"struct hyperlocal::server::Connecting\">Connecting</a>&lt;F&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;F: <a class=\"trait\" href=\"https://docs.rs/futures/0.1/futures/future/trait.Future.html\" title=\"trait futures::future::Future\">Future</a>,<br>&nbsp;&nbsp;&nbsp;&nbsp;F::<a class=\"type\" href=\"https://docs.rs/futures/0.1/futures/future/trait.Future.html#associatedtype.Item\" title=\"type futures::future::Future::Item\">Item</a>: <a class=\"trait\" href=\"https://docs.rs/hyper/0.12.10/hyper/service/service/trait.Service.html\" title=\"trait hyper::service::service::Service\">Service</a>&lt;ReqBody = <a class=\"struct\" href=\"https://docs.rs/hyper/0.12.10/hyper/body/body/struct.Body.html\" title=\"struct hyper::body::body::Body\">Body</a>&gt;,<br>&nbsp;&nbsp;&nbsp;&nbsp;&lt;F::<a class=\"type\" href=\"https://docs.rs/futures/0.1/futures/future/trait.Future.html#associatedtype.Item\" title=\"type futures::future::Future::Item\">Item</a> as <a class=\"trait\" href=\"https://docs.rs/hyper/0.12.10/hyper/service/service/trait.Service.html\" title=\"trait hyper::service::service::Service\">Service</a>&gt;::<a class=\"type\" href=\"https://docs.rs/hyper/0.12.10/hyper/service/service/trait.Service.html#associatedtype.ResBody\" title=\"type hyper::service::service::Service::ResBody\">ResBody</a>: <a class=\"trait\" href=\"https://docs.rs/hyper/0.12.10/hyper/body/payload/trait.Payload.html\" title=\"trait hyper::body::payload::Payload\">Payload</a>,<br>&nbsp;&nbsp;&nbsp;&nbsp;&lt;F::<a class=\"type\" href=\"https://docs.rs/futures/0.1/futures/future/trait.Future.html#associatedtype.Item\" title=\"type futures::future::Future::Item\">Item</a> as <a class=\"trait\" href=\"https://docs.rs/hyper/0.12.10/hyper/service/service/trait.Service.html\" title=\"trait hyper::service::service::Service\">Service</a>&gt;::<a class=\"type\" href=\"https://docs.rs/hyper/0.12.10/hyper/service/service/trait.Service.html#associatedtype.Future\" title=\"type hyper::service::service::Service::Future\">Future</a>: <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> + 'static,&nbsp;</span>",synthetic:false,types:["hyperlocal::server::Connecting"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
